// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/xjob/flow/orm/ent/flow"
)

// FlowCreate is the builder for creating a Flow entity.
type FlowCreate struct {
	config
	mutation *FlowMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *FlowCreate) SetCreateTime(v time.Time) *FlowCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *FlowCreate) SetNillableCreateTime(v *time.Time) *FlowCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *FlowCreate) SetUpdateTime(v time.Time) *FlowCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *FlowCreate) SetNillableUpdateTime(v *time.Time) *FlowCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetPk sets the "pk" field.
func (_c *FlowCreate) SetPk(v string) *FlowCreate {
	_c.mutation.SetPk(v)
	return _c
}

// SetStoreCode sets the "store_code" field.
func (_c *FlowCreate) SetStoreCode(v string) *FlowCreate {
	_c.mutation.SetStoreCode(v)
	return _c
}

// SetStoreName sets the "store_name" field.
func (_c *FlowCreate) SetStoreName(v string) *FlowCreate {
	_c.mutation.SetStoreName(v)
	return _c
}

// SetDt sets the "dt" field.
func (_c *FlowCreate) SetDt(v string) *FlowCreate {
	_c.mutation.SetDt(v)
	return _c
}

// SetInTotal sets the "in_total" field.
func (_c *FlowCreate) SetInTotal(v int) *FlowCreate {
	_c.mutation.SetInTotal(v)
	return _c
}

// SetNillableInTotal sets the "in_total" field if the given value is not nil.
func (_c *FlowCreate) SetNillableInTotal(v *int) *FlowCreate {
	if v != nil {
		_c.SetInTotal(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FlowCreate) SetID(v string) *FlowCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FlowCreate) SetNillableID(v *string) *FlowCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the FlowMutation object of the builder.
func (_c *FlowCreate) Mutation() *FlowMutation {
	return _c.mutation
}

// Save creates the Flow in the database.
func (_c *FlowCreate) Save(ctx context.Context) (*Flow, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FlowCreate) SaveX(ctx context.Context) *Flow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlowCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlowCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FlowCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := flow.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := flow.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.InTotal(); !ok {
		v := flow.DefaultInTotal
		_c.mutation.SetInTotal(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := flow.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FlowCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Flow.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Flow.update_time"`)}
	}
	if _, ok := _c.mutation.Pk(); !ok {
		return &ValidationError{Name: "pk", err: errors.New(`ent: missing required field "Flow.pk"`)}
	}
	if v, ok := _c.mutation.Pk(); ok {
		if err := flow.PkValidator(v); err != nil {
			return &ValidationError{Name: "pk", err: fmt.Errorf(`ent: validator failed for field "Flow.pk": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StoreCode(); !ok {
		return &ValidationError{Name: "store_code", err: errors.New(`ent: missing required field "Flow.store_code"`)}
	}
	if v, ok := _c.mutation.StoreCode(); ok {
		if err := flow.StoreCodeValidator(v); err != nil {
			return &ValidationError{Name: "store_code", err: fmt.Errorf(`ent: validator failed for field "Flow.store_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StoreName(); !ok {
		return &ValidationError{Name: "store_name", err: errors.New(`ent: missing required field "Flow.store_name"`)}
	}
	if v, ok := _c.mutation.StoreName(); ok {
		if err := flow.StoreNameValidator(v); err != nil {
			return &ValidationError{Name: "store_name", err: fmt.Errorf(`ent: validator failed for field "Flow.store_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Dt(); !ok {
		return &ValidationError{Name: "dt", err: errors.New(`ent: missing required field "Flow.dt"`)}
	}
	if v, ok := _c.mutation.Dt(); ok {
		if err := flow.DtValidator(v); err != nil {
			return &ValidationError{Name: "dt", err: fmt.Errorf(`ent: validator failed for field "Flow.dt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InTotal(); !ok {
		return &ValidationError{Name: "in_total", err: errors.New(`ent: missing required field "Flow.in_total"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := flow.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Flow.id": %w`, err)}
		}
	}
	return nil
}

func (_c *FlowCreate) sqlSave(ctx context.Context) (*Flow, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Flow.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FlowCreate) createSpec() (*Flow, *sqlgraph.CreateSpec) {
	var (
		_node = &Flow{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(flow.Table, sqlgraph.NewFieldSpec(flow.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(flow.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(flow.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Pk(); ok {
		_spec.SetField(flow.FieldPk, field.TypeString, value)
		_node.Pk = value
	}
	if value, ok := _c.mutation.StoreCode(); ok {
		_spec.SetField(flow.FieldStoreCode, field.TypeString, value)
		_node.StoreCode = value
	}
	if value, ok := _c.mutation.StoreName(); ok {
		_spec.SetField(flow.FieldStoreName, field.TypeString, value)
		_node.StoreName = value
	}
	if value, ok := _c.mutation.Dt(); ok {
		_spec.SetField(flow.FieldDt, field.TypeString, value)
		_node.Dt = value
	}
	if value, ok := _c.mutation.InTotal(); ok {
		_spec.SetField(flow.FieldInTotal, field.TypeInt, value)
		_node.InTotal = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Flow.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FlowUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *FlowCreate) OnConflict(opts ...sql.ConflictOption) *FlowUpsertOne {
	_c.conflict = opts
	return &FlowUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Flow.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FlowCreate) OnConflictColumns(columns ...string) *FlowUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FlowUpsertOne{
		create: _c,
	}
}

type (
	// FlowUpsertOne is the builder for "upsert"-ing
	//  one Flow node.
	FlowUpsertOne struct {
		create *FlowCreate
	}

	// FlowUpsert is the "OnConflict" setter.
	FlowUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *FlowUpsert) SetUpdateTime(v time.Time) *FlowUpsert {
	u.Set(flow.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *FlowUpsert) UpdateUpdateTime() *FlowUpsert {
	u.SetExcluded(flow.FieldUpdateTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Flow.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(flow.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FlowUpsertOne) UpdateNewValues() *FlowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(flow.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(flow.FieldCreateTime)
		}
		if _, exists := u.create.mutation.Pk(); exists {
			s.SetIgnore(flow.FieldPk)
		}
		if _, exists := u.create.mutation.StoreCode(); exists {
			s.SetIgnore(flow.FieldStoreCode)
		}
		if _, exists := u.create.mutation.StoreName(); exists {
			s.SetIgnore(flow.FieldStoreName)
		}
		if _, exists := u.create.mutation.Dt(); exists {
			s.SetIgnore(flow.FieldDt)
		}
		if _, exists := u.create.mutation.InTotal(); exists {
			s.SetIgnore(flow.FieldInTotal)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Flow.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FlowUpsertOne) Ignore() *FlowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FlowUpsertOne) DoNothing() *FlowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FlowCreate.OnConflict
// documentation for more info.
func (u *FlowUpsertOne) Update(set func(*FlowUpsert)) *FlowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FlowUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *FlowUpsertOne) SetUpdateTime(v time.Time) *FlowUpsertOne {
	return u.Update(func(s *FlowUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *FlowUpsertOne) UpdateUpdateTime() *FlowUpsertOne {
	return u.Update(func(s *FlowUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *FlowUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FlowCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FlowUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FlowUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: FlowUpsertOne.ID is not supported by MySQL driver. Use FlowUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FlowUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FlowCreateBulk is the builder for creating many Flow entities in bulk.
type FlowCreateBulk struct {
	config
	err      error
	builders []*FlowCreate
	conflict []sql.ConflictOption
}

// Save creates the Flow entities in the database.
func (_c *FlowCreateBulk) Save(ctx context.Context) ([]*Flow, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Flow, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FlowMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FlowCreateBulk) SaveX(ctx context.Context) []*Flow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlowCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlowCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Flow.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FlowUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *FlowCreateBulk) OnConflict(opts ...sql.ConflictOption) *FlowUpsertBulk {
	_c.conflict = opts
	return &FlowUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Flow.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FlowCreateBulk) OnConflictColumns(columns ...string) *FlowUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FlowUpsertBulk{
		create: _c,
	}
}

// FlowUpsertBulk is the builder for "upsert"-ing
// a bulk of Flow nodes.
type FlowUpsertBulk struct {
	create *FlowCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Flow.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(flow.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FlowUpsertBulk) UpdateNewValues() *FlowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(flow.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(flow.FieldCreateTime)
			}
			if _, exists := b.mutation.Pk(); exists {
				s.SetIgnore(flow.FieldPk)
			}
			if _, exists := b.mutation.StoreCode(); exists {
				s.SetIgnore(flow.FieldStoreCode)
			}
			if _, exists := b.mutation.StoreName(); exists {
				s.SetIgnore(flow.FieldStoreName)
			}
			if _, exists := b.mutation.Dt(); exists {
				s.SetIgnore(flow.FieldDt)
			}
			if _, exists := b.mutation.InTotal(); exists {
				s.SetIgnore(flow.FieldInTotal)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Flow.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FlowUpsertBulk) Ignore() *FlowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FlowUpsertBulk) DoNothing() *FlowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FlowCreateBulk.OnConflict
// documentation for more info.
func (u *FlowUpsertBulk) Update(set func(*FlowUpsert)) *FlowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FlowUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *FlowUpsertBulk) SetUpdateTime(v time.Time) *FlowUpsertBulk {
	return u.Update(func(s *FlowUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *FlowUpsertBulk) UpdateUpdateTime() *FlowUpsertBulk {
	return u.Update(func(s *FlowUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *FlowUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FlowCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FlowCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FlowUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
