// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/xjob/flow/orm/ent/flow"
	"github.com/twiglab/xjob/flow/orm/ent/predicate"
)

// FlowUpdate is the builder for updating Flow entities.
type FlowUpdate struct {
	config
	hooks    []Hook
	mutation *FlowMutation
}

// Where appends a list predicates to the FlowUpdate builder.
func (_u *FlowUpdate) Where(ps ...predicate.Flow) *FlowUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *FlowUpdate) SetUpdateTime(v time.Time) *FlowUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the FlowMutation object of the builder.
func (_u *FlowUpdate) Mutation() *FlowMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FlowUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlowUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FlowUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlowUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FlowUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := flow.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *FlowUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(flow.Table, flow.Columns, sqlgraph.NewFieldSpec(flow.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(flow.FieldUpdateTime, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FlowUpdateOne is the builder for updating a single Flow entity.
type FlowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlowMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *FlowUpdateOne) SetUpdateTime(v time.Time) *FlowUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the FlowMutation object of the builder.
func (_u *FlowUpdateOne) Mutation() *FlowMutation {
	return _u.mutation
}

// Where appends a list predicates to the FlowUpdate builder.
func (_u *FlowUpdateOne) Where(ps ...predicate.Flow) *FlowUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FlowUpdateOne) Select(field string, fields ...string) *FlowUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Flow entity.
func (_u *FlowUpdateOne) Save(ctx context.Context) (*Flow, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlowUpdateOne) SaveX(ctx context.Context) *Flow {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FlowUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlowUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FlowUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := flow.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *FlowUpdateOne) sqlSave(ctx context.Context) (_node *Flow, err error) {
	_spec := sqlgraph.NewUpdateSpec(flow.Table, flow.Columns, sqlgraph.NewFieldSpec(flow.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Flow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flow.FieldID)
		for _, f := range fields {
			if !flow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(flow.FieldUpdateTime, field.TypeTime, value)
	}
	_node = &Flow{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
