// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/twiglab/xjob/flow/orm/ent/flow"
)

// Flow is the model entity for the Flow schema.
type Flow struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// pk
	Pk string `json:"pk,omitempty"`
	// 编码
	StoreCode string `json:"store_code,omitempty"`
	// 名称
	StoreName string `json:"store_name,omitempty"`
	// Dt holds the value of the "dt" field.
	Dt string `json:"dt,omitempty"`
	// 总进入人数
	InTotal      int `json:"in_total,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Flow) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case flow.FieldInTotal:
			values[i] = new(sql.NullInt64)
		case flow.FieldID, flow.FieldPk, flow.FieldStoreCode, flow.FieldStoreName, flow.FieldDt:
			values[i] = new(sql.NullString)
		case flow.FieldCreateTime, flow.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Flow fields.
func (_m *Flow) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case flow.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case flow.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case flow.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case flow.FieldPk:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pk", values[i])
			} else if value.Valid {
				_m.Pk = value.String
			}
		case flow.FieldStoreCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field store_code", values[i])
			} else if value.Valid {
				_m.StoreCode = value.String
			}
		case flow.FieldStoreName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field store_name", values[i])
			} else if value.Valid {
				_m.StoreName = value.String
			}
		case flow.FieldDt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dt", values[i])
			} else if value.Valid {
				_m.Dt = value.String
			}
		case flow.FieldInTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field in_total", values[i])
			} else if value.Valid {
				_m.InTotal = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Flow.
// This includes values selected through modifiers, order, etc.
func (_m *Flow) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Flow.
// Note that you need to call Flow.Unwrap() before calling this method if this Flow
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Flow) Update() *FlowUpdateOne {
	return NewFlowClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Flow entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Flow) Unwrap() *Flow {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Flow is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Flow) String() string {
	var builder strings.Builder
	builder.WriteString("Flow(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("pk=")
	builder.WriteString(_m.Pk)
	builder.WriteString(", ")
	builder.WriteString("store_code=")
	builder.WriteString(_m.StoreCode)
	builder.WriteString(", ")
	builder.WriteString("store_name=")
	builder.WriteString(_m.StoreName)
	builder.WriteString(", ")
	builder.WriteString("dt=")
	builder.WriteString(_m.Dt)
	builder.WriteString(", ")
	builder.WriteString("in_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.InTotal))
	builder.WriteByte(')')
	return builder.String()
}

// Flows is a parsable slice of Flow.
type Flows []*Flow
