// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/twiglab/xjob/flow/orm/ent/flow"
	"github.com/twiglab/xjob/flow/orm/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeFlow = "Flow"
)

// FlowMutation represents an operation that mutates the Flow nodes in the graph.
type FlowMutation struct {
	config
	op            Op
	typ           string
	id            *string
	create_time   *time.Time
	update_time   *time.Time
	pk            *string
	store_code    *string
	store_name    *string
	dt            *string
	in_total      *int
	addin_total   *int
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Flow, error)
	predicates    []predicate.Flow
}

var _ ent.Mutation = (*FlowMutation)(nil)

// flowOption allows management of the mutation configuration using functional options.
type flowOption func(*FlowMutation)

// newFlowMutation creates new mutation for the Flow entity.
func newFlowMutation(c config, op Op, opts ...flowOption) *FlowMutation {
	m := &FlowMutation{
		config:        c,
		op:            op,
		typ:           TypeFlow,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withFlowID sets the ID field of the mutation.
func withFlowID(id string) flowOption {
	return func(m *FlowMutation) {
		var (
			err   error
			once  sync.Once
			value *Flow
		)
		m.oldValue = func(ctx context.Context) (*Flow, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Flow.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withFlow sets the old Flow of the mutation.
func withFlow(node *Flow) flowOption {
	return func(m *FlowMutation) {
		m.oldValue = func(context.Context) (*Flow, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m FlowMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m FlowMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Flow entities.
func (m *FlowMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *FlowMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *FlowMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Flow.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreateTime sets the "create_time" field.
func (m *FlowMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *FlowMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the Flow entity.
// If the Flow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlowMutation) OldCreateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *FlowMutation) ResetCreateTime() {
	m.create_time = nil
}

// SetUpdateTime sets the "update_time" field.
func (m *FlowMutation) SetUpdateTime(t time.Time) {
	m.update_time = &t
}

// UpdateTime returns the value of the "update_time" field in the mutation.
func (m *FlowMutation) UpdateTime() (r time.Time, exists bool) {
	v := m.update_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateTime returns the old "update_time" field's value of the Flow entity.
// If the Flow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlowMutation) OldUpdateTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateTime: %w", err)
	}
	return oldValue.UpdateTime, nil
}

// ResetUpdateTime resets all changes to the "update_time" field.
func (m *FlowMutation) ResetUpdateTime() {
	m.update_time = nil
}

// SetPk sets the "pk" field.
func (m *FlowMutation) SetPk(s string) {
	m.pk = &s
}

// Pk returns the value of the "pk" field in the mutation.
func (m *FlowMutation) Pk() (r string, exists bool) {
	v := m.pk
	if v == nil {
		return
	}
	return *v, true
}

// OldPk returns the old "pk" field's value of the Flow entity.
// If the Flow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlowMutation) OldPk(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPk is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPk requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPk: %w", err)
	}
	return oldValue.Pk, nil
}

// ResetPk resets all changes to the "pk" field.
func (m *FlowMutation) ResetPk() {
	m.pk = nil
}

// SetStoreCode sets the "store_code" field.
func (m *FlowMutation) SetStoreCode(s string) {
	m.store_code = &s
}

// StoreCode returns the value of the "store_code" field in the mutation.
func (m *FlowMutation) StoreCode() (r string, exists bool) {
	v := m.store_code
	if v == nil {
		return
	}
	return *v, true
}

// OldStoreCode returns the old "store_code" field's value of the Flow entity.
// If the Flow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlowMutation) OldStoreCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStoreCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStoreCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStoreCode: %w", err)
	}
	return oldValue.StoreCode, nil
}

// ResetStoreCode resets all changes to the "store_code" field.
func (m *FlowMutation) ResetStoreCode() {
	m.store_code = nil
}

// SetStoreName sets the "store_name" field.
func (m *FlowMutation) SetStoreName(s string) {
	m.store_name = &s
}

// StoreName returns the value of the "store_name" field in the mutation.
func (m *FlowMutation) StoreName() (r string, exists bool) {
	v := m.store_name
	if v == nil {
		return
	}
	return *v, true
}

// OldStoreName returns the old "store_name" field's value of the Flow entity.
// If the Flow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlowMutation) OldStoreName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStoreName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStoreName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStoreName: %w", err)
	}
	return oldValue.StoreName, nil
}

// ResetStoreName resets all changes to the "store_name" field.
func (m *FlowMutation) ResetStoreName() {
	m.store_name = nil
}

// SetDt sets the "dt" field.
func (m *FlowMutation) SetDt(s string) {
	m.dt = &s
}

// Dt returns the value of the "dt" field in the mutation.
func (m *FlowMutation) Dt() (r string, exists bool) {
	v := m.dt
	if v == nil {
		return
	}
	return *v, true
}

// OldDt returns the old "dt" field's value of the Flow entity.
// If the Flow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlowMutation) OldDt(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDt: %w", err)
	}
	return oldValue.Dt, nil
}

// ResetDt resets all changes to the "dt" field.
func (m *FlowMutation) ResetDt() {
	m.dt = nil
}

// SetInTotal sets the "in_total" field.
func (m *FlowMutation) SetInTotal(i int) {
	m.in_total = &i
	m.addin_total = nil
}

// InTotal returns the value of the "in_total" field in the mutation.
func (m *FlowMutation) InTotal() (r int, exists bool) {
	v := m.in_total
	if v == nil {
		return
	}
	return *v, true
}

// OldInTotal returns the old "in_total" field's value of the Flow entity.
// If the Flow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlowMutation) OldInTotal(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInTotal is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInTotal requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInTotal: %w", err)
	}
	return oldValue.InTotal, nil
}

// AddInTotal adds i to the "in_total" field.
func (m *FlowMutation) AddInTotal(i int) {
	if m.addin_total != nil {
		*m.addin_total += i
	} else {
		m.addin_total = &i
	}
}

// AddedInTotal returns the value that was added to the "in_total" field in this mutation.
func (m *FlowMutation) AddedInTotal() (r int, exists bool) {
	v := m.addin_total
	if v == nil {
		return
	}
	return *v, true
}

// ResetInTotal resets all changes to the "in_total" field.
func (m *FlowMutation) ResetInTotal() {
	m.in_total = nil
	m.addin_total = nil
}

// Where appends a list predicates to the FlowMutation builder.
func (m *FlowMutation) Where(ps ...predicate.Flow) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the FlowMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *FlowMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Flow, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *FlowMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *FlowMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Flow).
func (m *FlowMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *FlowMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.create_time != nil {
		fields = append(fields, flow.FieldCreateTime)
	}
	if m.update_time != nil {
		fields = append(fields, flow.FieldUpdateTime)
	}
	if m.pk != nil {
		fields = append(fields, flow.FieldPk)
	}
	if m.store_code != nil {
		fields = append(fields, flow.FieldStoreCode)
	}
	if m.store_name != nil {
		fields = append(fields, flow.FieldStoreName)
	}
	if m.dt != nil {
		fields = append(fields, flow.FieldDt)
	}
	if m.in_total != nil {
		fields = append(fields, flow.FieldInTotal)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *FlowMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case flow.FieldCreateTime:
		return m.CreateTime()
	case flow.FieldUpdateTime:
		return m.UpdateTime()
	case flow.FieldPk:
		return m.Pk()
	case flow.FieldStoreCode:
		return m.StoreCode()
	case flow.FieldStoreName:
		return m.StoreName()
	case flow.FieldDt:
		return m.Dt()
	case flow.FieldInTotal:
		return m.InTotal()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *FlowMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case flow.FieldCreateTime:
		return m.OldCreateTime(ctx)
	case flow.FieldUpdateTime:
		return m.OldUpdateTime(ctx)
	case flow.FieldPk:
		return m.OldPk(ctx)
	case flow.FieldStoreCode:
		return m.OldStoreCode(ctx)
	case flow.FieldStoreName:
		return m.OldStoreName(ctx)
	case flow.FieldDt:
		return m.OldDt(ctx)
	case flow.FieldInTotal:
		return m.OldInTotal(ctx)
	}
	return nil, fmt.Errorf("unknown Flow field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FlowMutation) SetField(name string, value ent.Value) error {
	switch name {
	case flow.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	case flow.FieldUpdateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateTime(v)
		return nil
	case flow.FieldPk:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPk(v)
		return nil
	case flow.FieldStoreCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStoreCode(v)
		return nil
	case flow.FieldStoreName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStoreName(v)
		return nil
	case flow.FieldDt:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDt(v)
		return nil
	case flow.FieldInTotal:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInTotal(v)
		return nil
	}
	return fmt.Errorf("unknown Flow field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *FlowMutation) AddedFields() []string {
	var fields []string
	if m.addin_total != nil {
		fields = append(fields, flow.FieldInTotal)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *FlowMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case flow.FieldInTotal:
		return m.AddedInTotal()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FlowMutation) AddField(name string, value ent.Value) error {
	switch name {
	case flow.FieldInTotal:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddInTotal(v)
		return nil
	}
	return fmt.Errorf("unknown Flow numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *FlowMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *FlowMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *FlowMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Flow nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *FlowMutation) ResetField(name string) error {
	switch name {
	case flow.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	case flow.FieldUpdateTime:
		m.ResetUpdateTime()
		return nil
	case flow.FieldPk:
		m.ResetPk()
		return nil
	case flow.FieldStoreCode:
		m.ResetStoreCode()
		return nil
	case flow.FieldStoreName:
		m.ResetStoreName()
		return nil
	case flow.FieldDt:
		m.ResetDt()
		return nil
	case flow.FieldInTotal:
		m.ResetInTotal()
		return nil
	}
	return fmt.Errorf("unknown Flow field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *FlowMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *FlowMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *FlowMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *FlowMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *FlowMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *FlowMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *FlowMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Flow unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *FlowMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Flow edge %s", name)
}
