// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/twiglab/xjob/flow/orm/ent/flow"
	"github.com/twiglab/xjob/flow/orm/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	flowMixin := schema.Flow{}.Mixin()
	flowMixinFields0 := flowMixin[0].Fields()
	_ = flowMixinFields0
	flowFields := schema.Flow{}.Fields()
	_ = flowFields
	// flowDescCreateTime is the schema descriptor for create_time field.
	flowDescCreateTime := flowMixinFields0[0].Descriptor()
	// flow.DefaultCreateTime holds the default value on creation for the create_time field.
	flow.DefaultCreateTime = flowDescCreateTime.Default.(func() time.Time)
	// flowDescUpdateTime is the schema descriptor for update_time field.
	flowDescUpdateTime := flowMixinFields0[1].Descriptor()
	// flow.DefaultUpdateTime holds the default value on creation for the update_time field.
	flow.DefaultUpdateTime = flowDescUpdateTime.Default.(func() time.Time)
	// flow.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	flow.UpdateDefaultUpdateTime = flowDescUpdateTime.UpdateDefault.(func() time.Time)
	// flowDescPk is the schema descriptor for pk field.
	flowDescPk := flowFields[1].Descriptor()
	// flow.PkValidator is a validator for the "pk" field. It is called by the builders before save.
	flow.PkValidator = flowDescPk.Validators[0].(func(string) error)
	// flowDescStoreCode is the schema descriptor for store_code field.
	flowDescStoreCode := flowFields[2].Descriptor()
	// flow.StoreCodeValidator is a validator for the "store_code" field. It is called by the builders before save.
	flow.StoreCodeValidator = flowDescStoreCode.Validators[0].(func(string) error)
	// flowDescStoreName is the schema descriptor for store_name field.
	flowDescStoreName := flowFields[3].Descriptor()
	// flow.StoreNameValidator is a validator for the "store_name" field. It is called by the builders before save.
	flow.StoreNameValidator = flowDescStoreName.Validators[0].(func(string) error)
	// flowDescDt is the schema descriptor for dt field.
	flowDescDt := flowFields[4].Descriptor()
	// flow.DtValidator is a validator for the "dt" field. It is called by the builders before save.
	flow.DtValidator = flowDescDt.Validators[0].(func(string) error)
	// flowDescInTotal is the schema descriptor for in_total field.
	flowDescInTotal := flowFields[5].Descriptor()
	// flow.DefaultInTotal holds the default value on creation for the in_total field.
	flow.DefaultInTotal = flowDescInTotal.Default.(int)
	// flowDescID is the schema descriptor for id field.
	flowDescID := flowFields[0].Descriptor()
	// flow.DefaultID holds the default value on creation for the id field.
	flow.DefaultID = flowDescID.Default.(func() string)
	// flow.IDValidator is a validator for the "id" field. It is called by the builders before save.
	flow.IDValidator = flowDescID.Validators[0].(func(string) error)
}
