// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GFlowEntryColumns holds the columns for the "g_flow_entry" table.
	GFlowEntryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"mysql": "char(36)", "postgres": "char(36)", "sqlite3": "char(36)"}},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "pk", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(64)", "postgres": "varchar(64)", "sqlite3": "varchar(64)"}},
		{Name: "store_code", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(64)", "postgres": "varchar(64)", "sqlite3": "varchar(64)"}},
		{Name: "store_name", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(64)", "postgres": "varchar(64)", "sqlite3": "varchar(64)"}},
		{Name: "dt", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(64)", "postgres": "varchar(64)", "sqlite3": "varchar(64)"}},
		{Name: "in_total", Type: field.TypeInt, Default: 0},
	}
	// GFlowEntryTable holds the schema information for the "g_flow_entry" table.
	GFlowEntryTable = &schema.Table{
		Name:       "g_flow_entry",
		Columns:    GFlowEntryColumns,
		PrimaryKey: []*schema.Column{GFlowEntryColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "flow_pk",
				Unique:  true,
				Columns: []*schema.Column{GFlowEntryColumns[3]},
			},
			{
				Name:    "flow_dt",
				Unique:  false,
				Columns: []*schema.Column{GFlowEntryColumns[6]},
			},
			{
				Name:    "flow_store_code",
				Unique:  false,
				Columns: []*schema.Column{GFlowEntryColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GFlowEntryTable,
	}
)

func init() {
	GFlowEntryTable.Annotation = &entsql.Annotation{
		Table: "g_flow_entry",
	}
}
