// Code generated by ent, DO NOT EDIT.

package flow

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the flow type in the database.
	Label = "flow"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldPk holds the string denoting the pk field in the database.
	FieldPk = "pk"
	// FieldStoreCode holds the string denoting the store_code field in the database.
	FieldStoreCode = "store_code"
	// FieldStoreName holds the string denoting the store_name field in the database.
	FieldStoreName = "store_name"
	// FieldDt holds the string denoting the dt field in the database.
	FieldDt = "dt"
	// FieldInTotal holds the string denoting the in_total field in the database.
	FieldInTotal = "in_total"
	// Table holds the table name of the flow in the database.
	Table = "g_flow_entry"
)

// Columns holds all SQL columns for flow fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldPk,
	FieldStoreCode,
	FieldStoreName,
	FieldDt,
	FieldInTotal,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// PkValidator is a validator for the "pk" field. It is called by the builders before save.
	PkValidator func(string) error
	// StoreCodeValidator is a validator for the "store_code" field. It is called by the builders before save.
	StoreCodeValidator func(string) error
	// StoreNameValidator is a validator for the "store_name" field. It is called by the builders before save.
	StoreNameValidator func(string) error
	// DtValidator is a validator for the "dt" field. It is called by the builders before save.
	DtValidator func(string) error
	// DefaultInTotal holds the default value on creation for the "in_total" field.
	DefaultInTotal int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Flow queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByPk orders the results by the pk field.
func ByPk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPk, opts...).ToFunc()
}

// ByStoreCode orders the results by the store_code field.
func ByStoreCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoreCode, opts...).ToFunc()
}

// ByStoreName orders the results by the store_name field.
func ByStoreName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoreName, opts...).ToFunc()
}

// ByDt orders the results by the dt field.
func ByDt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDt, opts...).ToFunc()
}

// ByInTotal orders the results by the in_total field.
func ByInTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInTotal, opts...).ToFunc()
}
