// Code generated by ent, DO NOT EDIT.

package flow

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/twiglab/xjob/flow/orm/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Flow {
	return predicate.Flow(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Flow {
	return predicate.Flow(sql.FieldContainsFold(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldUpdateTime, v))
}

// Pk applies equality check predicate on the "pk" field. It's identical to PkEQ.
func Pk(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldPk, v))
}

// StoreCode applies equality check predicate on the "store_code" field. It's identical to StoreCodeEQ.
func StoreCode(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldStoreCode, v))
}

// StoreName applies equality check predicate on the "store_name" field. It's identical to StoreNameEQ.
func StoreName(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldStoreName, v))
}

// Dt applies equality check predicate on the "dt" field. It's identical to DtEQ.
func Dt(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldDt, v))
}

// InTotal applies equality check predicate on the "in_total" field. It's identical to InTotalEQ.
func InTotal(v int) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldInTotal, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldUpdateTime, v))
}

// PkEQ applies the EQ predicate on the "pk" field.
func PkEQ(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldPk, v))
}

// PkNEQ applies the NEQ predicate on the "pk" field.
func PkNEQ(v string) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldPk, v))
}

// PkIn applies the In predicate on the "pk" field.
func PkIn(vs ...string) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldPk, vs...))
}

// PkNotIn applies the NotIn predicate on the "pk" field.
func PkNotIn(vs ...string) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldPk, vs...))
}

// PkGT applies the GT predicate on the "pk" field.
func PkGT(v string) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldPk, v))
}

// PkGTE applies the GTE predicate on the "pk" field.
func PkGTE(v string) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldPk, v))
}

// PkLT applies the LT predicate on the "pk" field.
func PkLT(v string) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldPk, v))
}

// PkLTE applies the LTE predicate on the "pk" field.
func PkLTE(v string) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldPk, v))
}

// PkContains applies the Contains predicate on the "pk" field.
func PkContains(v string) predicate.Flow {
	return predicate.Flow(sql.FieldContains(FieldPk, v))
}

// PkHasPrefix applies the HasPrefix predicate on the "pk" field.
func PkHasPrefix(v string) predicate.Flow {
	return predicate.Flow(sql.FieldHasPrefix(FieldPk, v))
}

// PkHasSuffix applies the HasSuffix predicate on the "pk" field.
func PkHasSuffix(v string) predicate.Flow {
	return predicate.Flow(sql.FieldHasSuffix(FieldPk, v))
}

// PkEqualFold applies the EqualFold predicate on the "pk" field.
func PkEqualFold(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEqualFold(FieldPk, v))
}

// PkContainsFold applies the ContainsFold predicate on the "pk" field.
func PkContainsFold(v string) predicate.Flow {
	return predicate.Flow(sql.FieldContainsFold(FieldPk, v))
}

// StoreCodeEQ applies the EQ predicate on the "store_code" field.
func StoreCodeEQ(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldStoreCode, v))
}

// StoreCodeNEQ applies the NEQ predicate on the "store_code" field.
func StoreCodeNEQ(v string) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldStoreCode, v))
}

// StoreCodeIn applies the In predicate on the "store_code" field.
func StoreCodeIn(vs ...string) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldStoreCode, vs...))
}

// StoreCodeNotIn applies the NotIn predicate on the "store_code" field.
func StoreCodeNotIn(vs ...string) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldStoreCode, vs...))
}

// StoreCodeGT applies the GT predicate on the "store_code" field.
func StoreCodeGT(v string) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldStoreCode, v))
}

// StoreCodeGTE applies the GTE predicate on the "store_code" field.
func StoreCodeGTE(v string) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldStoreCode, v))
}

// StoreCodeLT applies the LT predicate on the "store_code" field.
func StoreCodeLT(v string) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldStoreCode, v))
}

// StoreCodeLTE applies the LTE predicate on the "store_code" field.
func StoreCodeLTE(v string) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldStoreCode, v))
}

// StoreCodeContains applies the Contains predicate on the "store_code" field.
func StoreCodeContains(v string) predicate.Flow {
	return predicate.Flow(sql.FieldContains(FieldStoreCode, v))
}

// StoreCodeHasPrefix applies the HasPrefix predicate on the "store_code" field.
func StoreCodeHasPrefix(v string) predicate.Flow {
	return predicate.Flow(sql.FieldHasPrefix(FieldStoreCode, v))
}

// StoreCodeHasSuffix applies the HasSuffix predicate on the "store_code" field.
func StoreCodeHasSuffix(v string) predicate.Flow {
	return predicate.Flow(sql.FieldHasSuffix(FieldStoreCode, v))
}

// StoreCodeEqualFold applies the EqualFold predicate on the "store_code" field.
func StoreCodeEqualFold(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEqualFold(FieldStoreCode, v))
}

// StoreCodeContainsFold applies the ContainsFold predicate on the "store_code" field.
func StoreCodeContainsFold(v string) predicate.Flow {
	return predicate.Flow(sql.FieldContainsFold(FieldStoreCode, v))
}

// StoreNameEQ applies the EQ predicate on the "store_name" field.
func StoreNameEQ(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldStoreName, v))
}

// StoreNameNEQ applies the NEQ predicate on the "store_name" field.
func StoreNameNEQ(v string) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldStoreName, v))
}

// StoreNameIn applies the In predicate on the "store_name" field.
func StoreNameIn(vs ...string) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldStoreName, vs...))
}

// StoreNameNotIn applies the NotIn predicate on the "store_name" field.
func StoreNameNotIn(vs ...string) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldStoreName, vs...))
}

// StoreNameGT applies the GT predicate on the "store_name" field.
func StoreNameGT(v string) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldStoreName, v))
}

// StoreNameGTE applies the GTE predicate on the "store_name" field.
func StoreNameGTE(v string) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldStoreName, v))
}

// StoreNameLT applies the LT predicate on the "store_name" field.
func StoreNameLT(v string) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldStoreName, v))
}

// StoreNameLTE applies the LTE predicate on the "store_name" field.
func StoreNameLTE(v string) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldStoreName, v))
}

// StoreNameContains applies the Contains predicate on the "store_name" field.
func StoreNameContains(v string) predicate.Flow {
	return predicate.Flow(sql.FieldContains(FieldStoreName, v))
}

// StoreNameHasPrefix applies the HasPrefix predicate on the "store_name" field.
func StoreNameHasPrefix(v string) predicate.Flow {
	return predicate.Flow(sql.FieldHasPrefix(FieldStoreName, v))
}

// StoreNameHasSuffix applies the HasSuffix predicate on the "store_name" field.
func StoreNameHasSuffix(v string) predicate.Flow {
	return predicate.Flow(sql.FieldHasSuffix(FieldStoreName, v))
}

// StoreNameEqualFold applies the EqualFold predicate on the "store_name" field.
func StoreNameEqualFold(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEqualFold(FieldStoreName, v))
}

// StoreNameContainsFold applies the ContainsFold predicate on the "store_name" field.
func StoreNameContainsFold(v string) predicate.Flow {
	return predicate.Flow(sql.FieldContainsFold(FieldStoreName, v))
}

// DtEQ applies the EQ predicate on the "dt" field.
func DtEQ(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldDt, v))
}

// DtNEQ applies the NEQ predicate on the "dt" field.
func DtNEQ(v string) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldDt, v))
}

// DtIn applies the In predicate on the "dt" field.
func DtIn(vs ...string) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldDt, vs...))
}

// DtNotIn applies the NotIn predicate on the "dt" field.
func DtNotIn(vs ...string) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldDt, vs...))
}

// DtGT applies the GT predicate on the "dt" field.
func DtGT(v string) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldDt, v))
}

// DtGTE applies the GTE predicate on the "dt" field.
func DtGTE(v string) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldDt, v))
}

// DtLT applies the LT predicate on the "dt" field.
func DtLT(v string) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldDt, v))
}

// DtLTE applies the LTE predicate on the "dt" field.
func DtLTE(v string) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldDt, v))
}

// DtContains applies the Contains predicate on the "dt" field.
func DtContains(v string) predicate.Flow {
	return predicate.Flow(sql.FieldContains(FieldDt, v))
}

// DtHasPrefix applies the HasPrefix predicate on the "dt" field.
func DtHasPrefix(v string) predicate.Flow {
	return predicate.Flow(sql.FieldHasPrefix(FieldDt, v))
}

// DtHasSuffix applies the HasSuffix predicate on the "dt" field.
func DtHasSuffix(v string) predicate.Flow {
	return predicate.Flow(sql.FieldHasSuffix(FieldDt, v))
}

// DtEqualFold applies the EqualFold predicate on the "dt" field.
func DtEqualFold(v string) predicate.Flow {
	return predicate.Flow(sql.FieldEqualFold(FieldDt, v))
}

// DtContainsFold applies the ContainsFold predicate on the "dt" field.
func DtContainsFold(v string) predicate.Flow {
	return predicate.Flow(sql.FieldContainsFold(FieldDt, v))
}

// InTotalEQ applies the EQ predicate on the "in_total" field.
func InTotalEQ(v int) predicate.Flow {
	return predicate.Flow(sql.FieldEQ(FieldInTotal, v))
}

// InTotalNEQ applies the NEQ predicate on the "in_total" field.
func InTotalNEQ(v int) predicate.Flow {
	return predicate.Flow(sql.FieldNEQ(FieldInTotal, v))
}

// InTotalIn applies the In predicate on the "in_total" field.
func InTotalIn(vs ...int) predicate.Flow {
	return predicate.Flow(sql.FieldIn(FieldInTotal, vs...))
}

// InTotalNotIn applies the NotIn predicate on the "in_total" field.
func InTotalNotIn(vs ...int) predicate.Flow {
	return predicate.Flow(sql.FieldNotIn(FieldInTotal, vs...))
}

// InTotalGT applies the GT predicate on the "in_total" field.
func InTotalGT(v int) predicate.Flow {
	return predicate.Flow(sql.FieldGT(FieldInTotal, v))
}

// InTotalGTE applies the GTE predicate on the "in_total" field.
func InTotalGTE(v int) predicate.Flow {
	return predicate.Flow(sql.FieldGTE(FieldInTotal, v))
}

// InTotalLT applies the LT predicate on the "in_total" field.
func InTotalLT(v int) predicate.Flow {
	return predicate.Flow(sql.FieldLT(FieldInTotal, v))
}

// InTotalLTE applies the LTE predicate on the "in_total" field.
func InTotalLTE(v int) predicate.Flow {
	return predicate.Flow(sql.FieldLTE(FieldInTotal, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Flow) predicate.Flow {
	return predicate.Flow(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Flow) predicate.Flow {
	return predicate.Flow(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Flow) predicate.Flow {
	return predicate.Flow(sql.NotPredicates(p))
}
